name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dlist
          artifact_name: dlist-${{ matrix.node-version }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: dlist-18.x
