name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Instala Node.js (>=18 para crypto.getRandomValues)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      # 3) Instala dependencias
      - name: Install dependencies
        run: npm ci

      # 4) Construye la aplicación con Vite
      - name: Build app
        run: npm run build

      # 5) Despliega sólo la carpeta dist/ en la rama gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # rama destino
          folder: dist # carpeta generada por `npm run build`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
